config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'page/index'
  get '/businesses/search', to: 'businesses#search', as: :search

  root to: 'page#index'
    resources :restaurants do
        resources :recommendations, only: [:new, :create]
    end
    resources :shops do
    resources :reviews, only: [:new, :create]
  end

  resources :reviews, only: [:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/business.rb
class Business < ApplicationRecord
  has_many :shops
  has_many :restaurants
  searchkick
end

app/models/recommendation.rb
class Recommendation < ApplicationRecord
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :recommendations, dependent: :destroy
  has_many_attached :photos
  searchkick

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :shop
  belongs_to :user, optional: true
  has_many_attached :photos
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :reviews, dependent: :destroy
  has_many_attached :photos

  searchkick
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  def search
    @businesses = Business.all

    @restaurant = Restaurant.search(params[:query], where: {restaurant_id: params[:restauranr][:id]})
    @shops = Shop.search(params[:query], where: {shop_id: params[:shop][:id]})

  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
    def new
        @restaurant = Restaurant.find(params[:restaurant_id])
        @recommendation = Recommendation.new
    end

    def create
      @restaurant = Restaurant.find(params[:restaurant_id])
      @recommendation = Recommendation.new(recommendation_params)
      @recommendation.restaurant = @restaurant
      if @recommendation.save!
        redirect_to restaurant_path(@restaurant)
      else
        render "recommendations/new"
      end
    end

    private

    def recommendation_params
      params.require(:recommendation).permit(:content, :stars, photos: [])
    end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    # search condition
    # the `geocoded` scope filters only restaurants with coordinates (latitude & longitude)
    @restaurants = Restaurant.all

    @markers = @restaurants.geocoded.map do |restaurant|
      {
        lat: restaurant.latitude,
        lng: restaurant.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { restaurant: restaurant }),
        image_url: helpers.asset_url('https://upload.wikimedia.org/wikipedia/commons/6/62/Barbieri_-_ViaSophia25668.jpg')
      }
    end
  end

  def search
    # write a search for boxes and store in instance variable
    @restaurant = Restaurant.search(params[:query], where: {restaurant_id: params[:restauranr][:id]})
    # write a search for items and store in instance variable
  end

  def search
    # write a search for boxes and store in instance variable
    @restaurants = Restaurant.search(params[:query], where: {restaunt_id: params[:restaurant][:id]})
    # write a search for items and store in instance variable
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

   def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render 'new'
    end
  end

    def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    flash[:notice] = 'restaurants deleted successfully'
    redirect_to restaurants_path
  end

  private


  def build_geojson
    {
      type: "FeatureCollection",
      features: @restaurants.map(&:to_feature)
    }
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :description,:latitude, :longitude, :opening, photos: [])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def new
        @shop = Shop.find(params[:shop_id])
        @review = Review.new
    end

    def create
      @shop = Shop.find(params[:shop_id])
      @review = Review.new(review_params)
      @review.shop = @shop
      if @review.save!
        redirect_to shop_path(@shop)
      else
        render "reviews/new"
      end
    end
  
    private
  
    def review_params
      params.require(:review).permit(:content, photos: [])
    end
  end
  

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show, :search]

  def index
    @shops = Shop.all
  end

  def search
    # write a search for boxes and store in instance variable
    @shops = Shop.search(params[:query], where: {shop_id: params[:shop][:id]})
    # write a search for items and store in instance variable
  end

  def top
    @shops = Shop.where(stars: 5)

    # by default this is rendering app/views/shops/top.html.erb
    # but... we cna override this default behaviour
    # and tell rails exactly which view to render
    render "index"
  end

  def show
    @shop = Shop.find(params[:id])
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.create(shop_params)
    if @shop.save
      redirect_to shop_path(@shop)
    else
      render 'new'
    end
  end

  def edit
    @shop = Shop.find(params[:id])
  end

  def update
    @shop = Shop.find(params[:id])
    @shop.update(shop_params)

    redirect_to shop_path(shop)
  end

  def destroy
    @shop = Shop.find(params[:id])
    @shop.destroy
    flash[:notice] = 'Shops deleted successfully'
    redirect_to shops_path
  end

  private

  def shop_params
    params.require(:shop).permit(:name, :address, :stars,photos: [])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/businesses/search.html.erb
<div class="container">
  <h1>Results</h1>
  <br>
<%= form_tag search_path, method: :get do %>
  <%= hidden_field :business, value: @business %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Search your businesss"
  %>
  <%= submit_tag "Search", class: "btn btn-primary"%>
<% end %>

 <div class ="container">
      <% @business.shops.each do |shop| %>
          <div class="card-white">
            <div class="shop-card-item">
              <p><b>shop: </b><%= shop.name %></p>
            </div>
            <div class="shop-card-item">
              <p><b>Address: </b><%= shop.address %></p>
            </div>
            <div class="shop-card-item">
              <p><b>Stars: </b><%= shop.star %></p>
            </div>
            <div class="card-category"
      style="background-image: url('<%= cl_image_path shop.photos[0].key, height: 200, width: 300, crop: :fill %>')">        </td>
            <br>
           <% end %>

app/views/recommendations/new.html.erb
<h1>Leave a review for "<%= @restaurant.name %>"</h1>
  <div class="container">
  <!-- post /shops/:shop_id/reviews -->
  <!-- if simple form detects errors in `@review` it will display them in the form -->
    <%= simple_form_for([@restaurant, @recommendation]) do |f| %>
        <%= f.input :content %>
        <%= f.input :stars %>
        <%= f.input :photo, as: :file %>
      <%= f.button :submit, "Add a review", class: "btn btn-success" %>
    <% end %>
</div>

app/views/restaurants/_info_window.html.erb
<h2><%= restaurant.name %></h2>
<p><%= restaurant.address %></p>

app/views/restaurants/index.html.erb
<div id="container">
  <h1>Restaurants</h1>
    </div>

<div class="row">
      <div class="title">
        <a href="/restaurants/new", style="float: right;", class="btn btn-success">Add restaurants</a></span>
        </div>
          <% if @restaurants.any? %>
            <div class="col">
               <table class="table table-hover">
                <% @restaurants.each do |restaurant| %>
                  <thead>
                    <tr>
                      <th>Name</th>
                      <th>Description</th>
                      <th>Reviews</th>
                      </tr>
                      </thead>
                  <tbody>
                      <tr>
                        <td>
                          <h4><%= link_to restaurant.name, restaurant_path(restaurant) %></h4>
                            <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path restaurant.photos[0].key, height: 300, width: 400, crop: :fill %>')">
                            </td>
                            <td>
                              <p><%= restaurant.address %></p>
                                <%= link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant), class:"btn btn-default" %>
                                <%= link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete, class:"btn btn-default" %>
                            </td>
                              <td>
                                <% restaurant.recommendations.each do |recommendation| %>
                                  <p><%= recommendation.content %></p>
                              <% end %>
                                <h5>Average rating: <%#star_rating(restaurant.average_rating) %></h5>
                                  <%= link_to "Review #{restaurant.name}", new_restaurant_recommendation_path(restaurant), class:"btn btn-default" %>
                             </td>
                           </tr>
                       </tbody>
                     <% end %>
                    </table>
                  <%else %>
                    <h1>No restaurants yet</h1>
                 <% end %>
            </div>
          </div>
<div class="container">
  <div class="col">
        <div id="map"
        style="width: 100%; height: 600px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
    </div>
</div>
</div>

app/views/restaurants/new.html.erb
<%= simple_form_for(@restaurant, remote: true) do |f| %>
  <%= f.input :name, class:"col-sm-2 control-label" %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%# f.input :opening %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
    <div class="mt-3">
    <%= f.submit class: 'btn btn-primary' %>
    <%= link_to 'Cancel', restaurants_path, class: 'btn btn-danger ml-2' %>

    </div>
<% end %>

app/views/restaurants/search.html.erb
<div class="container">
  <h1>Results</h1>
  <br>
<%= form_tag search_path, method: :get do %>
  <%= hidden_field :restaurant, value: @restaurant %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Search your restaurants"
  %>
  <%= submit_tag "Search", class: "btn btn-primary"%>
<% end %>

 <div class ="container">
      <% @restaurants.each do |restaurant| %>
          <div class="card-white">
            <div class="restaurant-card-item">
              <p><b>restaurant: </b><%= restaurant.name %></p>
            </div>
            <div class="restaurant-card-item">
              <p><b>Address: </b><%= restaurant.address %></p>
            </div>

            <div class="card-category"
      style="background-image: url('<%= cl_image_path restaurant.photos[0].key, height: 200, width: 300, crop: :fill %>')">        </td>
            <br>
           <% end %>

app/views/restaurants/show.html.erb
<div class="container">
  <h1><%= @restaurant.name %></h1>
</div>
   <div class="row">
        <% if @restaurant.photos.nil? %>
   <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path "https://res.cloudinary.com/dwxhfawho/image/upload/v1605666098/air-moto/2018_Aprilia_Shiver_900/2018_Aprilia_Shiver_900_1_aiz6s2.jpg", height: 300, width: 400, crop: :fill %>')">
        <% else %>
    <img class="d-block w-100"  src= "<%= cl_image_path @restaurant.photos[0].key, crop: :fill %>", height: "300", width:"550">
    <br>
        <% end %>
</div>




<div class="col-md-6 offset-md-3 mt-5" style="margin:0 auto">
  <div class="card-header">
    The Restaurant
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item" id="name"><%= @restaurant.address %>
    <%= @restaurant.description %> <%= @restaurant.opening %>
    <br>
   <id="stars"> 4.93&#9733;       (32 bookings)</id></li>
    <li class="list-group-item"><strong>Location:</strong> <%= @restaurant.address %></li>
    <li class="list-group-item"><strong>Description:</strong> <%= @restaurant.description%></li>
    <li class="list-group-item"><strong>Opening Hours:</strong> <%# @restaurant.price%></li>
  </ul>
</div>
</div>


<div class="col-sm-12 col-md-6">
  <div class="col-md-6 offset-md-3 mt-5" style="margin:0 auto">
      <div class="card-header">
      <h3><%= link_to "Leave a review", new_restaurant_recommendation_path(@restaurant) %></h3>
  </div>
   <% @restaurant.recommendations.each do |recommendation| %>
     <ul class="list-group list-group-flush">
           <li class="list-group-item"><strong>Review:  </strong><%= recommendation.content %>
           <strong>Stars:  </strong><%= recommendation.stars %></id></li>
      </ul>
    <% end %>
      <p><%= link_to "Edit", edit_restaurant_path(@restaurant) %></p>
  <p><%= link_to "Delete", restaurant_path(@restaurant), method: :delete %></p>
</div>
</div>

app/views/reviews/new.html.erb
<h1>Leave a review for "<%= @shop.name %>"</h1>
<div class="container">
<!-- post /shops/:shop_id/reviews -->
<!-- if simple form detects errors in `@review` it will display them in the form -->
<%= simple_form_for([@shop, @review]) do |f| %>
  <%= f.input :content %>
    <%= f.input :photo, as: :file %>
    <%= f.button :submit, "Add a review", class: "btn btn-success" %>
<% end %>
</div>

app/views/shops/_form.html.erb
<%= simple_form_for(@shop, remote: true) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :star %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <div class="mt-3">
  <%= f.submit class: 'btn btn-primary' %>
  <%= link_to 'Cancel', shops_path, class: 'btn btn-danger ml-2' %>
  </div>
<% end %>

app/views/shops/index.html.erb
    <h1>Shops</h1>
<div class="title">
    <a href="/shops/new", style="float: right;", class="btn btn-success">Add shops</a></span>
</div>
    <% if @shops.any? %>
    <% @shops.each do |shop| %>
      <div class="container">
      <table class="table table-hover">
            <thead>
              <tr>
                <th>Shop Name</th>
                <th>Description</th>
                <th>Reviews</th>
              </tr>
            </thead>
                  <tbody>
                        <tr>
                          <td>
                        <h4><%= link_to shop.name, shop_path(shop) %></h4>
                        <div class="card-category"
                        style="background-image: url('<%= cl_image_path shop.photos[0].key, height: 200, width: 300, crop: :fill %>')">        </td>
                          <td>
                            <p><%= shop.address %></p>
                            <%= link_to "Edit #{shop.name}", edit_shop_path(shop), class:"btn btn-default" %>
                            <%= link_to "Delete #{shop.name}", shop_path(shop), method: :delete, class:"btn btn-default" %>
                          </td>
                          <td>
                          <% shop.reviews.each do |review| %>
                            <p><%= review.content %></p>
                          <% end %>
                            <h5>Average rating: <%#star_rating(shop.average_rating) %></h5>
                          <%= link_to "Review #{shop.name}", new_shop_review_path(shop), class:"btn btn-default" %>
                          </td>
                        </tr>
                  </tbody>
                  </table>
                  <% end %>
                  <%else %>
                  <h1>No shops yet</h1>
            <% end %>
  </div>
  </div>
</div>

app/views/shops/new.html.erb
<h1>New Shop</h1>
<div class="container">
<%= render "form" %>
</div>

app/views/shops/search.html.erb
<div class="container">
  <h1>Results</h1>
  <br>
<%= form_tag search_path, method: :get do %>
  <%= hidden_field :shop, value: @shop %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Search your shops"
  %>
  <%= submit_tag "Search", class: "btn btn-primary"%>
<% end %>

 <div class ="container">
      <% @shops.each do |shop| %>
          <div class="card-white">
            <div class="shop-card-item">
              <p><b>shop: </b><%= shop.name %></p>
            </div>
            <div class="shop-card-item">
              <p><b>Address: </b><%= shop.address %></p>
            </div>
            <div class="shop-card-item">
              <p><b>Stars: </b><%= shop.star %></p>
            </div>
            <div class="card-category"
      style="background-image: url('<%= cl_image_path shop.photos[0].key, height: 200, width: 300, crop: :fill %>')">        </td>
            <br>
           <% end %>

app/views/shops/show.html.erb
<div class="container">
  <h1><%= @shop.name %></h1>
</div>
  <div class="row">
      <% if @shop.photos.nil? %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path "https://res.cloudinary.com/dwxhfawho/image/upload/v1605666098/air-moto/2018_Aprilia_Shiver_900/2018_Aprilia_Shiver_900_1_aiz6s2.jpg", height: 300, width: 400, crop: :fill %>')">
      <% else %>
          <img class="d-block w-100"  src= "<%= cl_image_path @shop.photos[0].key, crop: :fill %>", height: "300", width:"550">
<br>
      <% end %>
<br>

<div class="col-md-6 offset-md-3 mt-5" style="margin:0 auto">
  <div class="card-header">
    <strong><%= @shop.name %></strong>
</div>
        <ul class="list-group list-group-flush">
        <li class="list-group-item" id="name"><strong>Address:  </strong><%= @shop.address %>
          <li class="list-group-item"><strong>Stars:  </strong> <%= @shop.star %></li>
          <div class="col-md-6 offset-md-3 mt-5" style="margin:0 auto">
             <div class="card-header">
                   <h3><%= link_to "Leave a review", new_shop_review_path(@shop) %></h3>
             </div>
                    <% @shop.reviews.each do |review| %>
                         <ul class="list-group list-group-flush">
                            <li class="list-group-item"><strong>Review:  </strong><%= review.content %>
                                  <strong>Photos:  </strong><%= review.photos[0] %>
                              </id>
                            </li>
                          </ul>
                    <% end %>
                      <p><%= link_to "Edit", edit_shop_path(@shop) %></p>
                      <p><%= link_to "Delete", shop_path(@shop), method: :delete %></p>
</div>
</div>